<?php

return [
	'tags_id_name' => [
					'tag1'  => 'Home feed',
			        'tag2'  => 'Popular',
			        'tag3'  => 'Everything',
			        'tag4'  => 'Gifts',
			        'tag5'  => 'Videos',
			        'tag6'  => 'Animals and pets',
			        'tag7'  => 'Architecture',
			        'tag8'  => 'Art',
			        'tag9'  => 'Cars and motocyles',
			        'tag10' => 'Celebrities',
			        'tag11' => 'DIY and crafts',
			        'tag12' => 'Design',
			        'tag13' => 'Education',
			        'tag14' => 'Entertainment',
			        'tag15' => 'Food and drink',
			        'tag16' => 'Gardening',
			        'tag17' => 'Geek',
			        'tag18' => 'Hair and beauty',
			        'tag19' => 'Health and fitness',
			        'tag20' => 'History',
			        'tag21' => 'Holidays and events',
			        'tag22' => 'Humor',
	],
	'tags_name_id' => [
					'Home feed' => 'tag1',
			        'Popular' => 'tag2',
			        'Everything' => 'tag3',
			        'Gifts' => 'tag4',
			        'Videos' => 'tag5',
			        'Animals and pets' => 'tag6',
			        'Architecture' => 'tag7',
			        'Art' => 'tag8',
			        'Cars and motocyles' => 'tag9',
			        'Celebrities' => 'tag10',
			        'DIY and crafts' => 'tag11',
			        'Design' => 'tag12',
			        'Education' => 'tag13',
			        'Entertainment' => 'tag14',
			        'Food and drink' => 'tag15',
			        'Gardening' => 'tag16',
			        'Geek' => 'tag17',
			        'Hair and beauty' => 'tag18',
			        'Health and fitness' => 'tag19',
			        'History' => 'tag20',
			        'Holidays and events' => 'tag21',
			        'Humor' => 'tag22',
	]
];